--INSERT INTO CATEGORY VALUES (1,'Eletrônicos e celulares',true)
--INSERT INTO CATEGORY VALUES (2,'Carros',false)


--INSERT INTO ROLE VALUES (1,'ROLE_CADASTRAR_CATEGORIA')
--INSERT INTO ROLE VALUES (2,'ROLE_ATUALIZAR_CATEGORIA')
--INSERT INTO ROLE VALUES (3,'ROLE_PESQUISAR_TODAS_CATEGORIA')
--INSERT INTO ROLE VALUES (4,'ROLE_ATUALIZAR_CATEGORIA_POR_ID')


--INSERT INTO USER VALUES (1,0,'2018-10-20 12:58:02','dmjesus@gmail.com',1,'Diego','$2a$10$7ZlAapc1KaZd7Yl1MbSOpO5ap24LmMZLareqM1M3oAOl5gijd8vs2',NULL,NULL,'Oliveira',NULL);

--INSERT INTO USER_ROLE VALUES (1,1)

INSERT INTO RISK VALUES (1,'A')
INSERT INTO RISK VALUES (2,'B')
INSERT INTO RISK VALUES (3,'C')